#!/bin/bash

if [[ ! -f ~/.ssh/id_rsa ]]
then
    ssh-keygen -t rsa
    ssh-copy-id -i ~/.ssh/id_rsa.pub root@localhost
fi

pushd `dirname $0`/../ansible
ansible-playbook update_authorized_keys_playbook.yml -i inventory/hosts.ini --ask-pass --ask-become-pass -u $1
