#!/bin/bash

if [[ ! -f ~/.ssh/id_rsa ]]
then
    ssh-keygen -t rsa
    cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
fi

rsync -r /root/.ssh/ $1@$2:~/.ssh/
ssh -t $1@$2 sudo rsync -r /home/$1/.ssh/ /root/.ssh/
