#!/bin/bash

echo Execute the scripts in this folder as needed.
echo The docker image can be run with 'docker run -it -v ~/.ssh:/root/.ssh <imagename> /scripts/<script>'

echo Scripts:
ls `dirname $0` -w 1