---
ansible_user: root
systemd_dir: /etc/systemd/system
compute_ip: "{{ hostvars[groups['compute'][0]]['ansible_host'] | default(groups['compute'][0]) }}"
load_balance_ip: 192.168.50.4
ansible_python_interpreter: /usr/bin/python3