---

- name: Install package requirements
  apt:
    name:
      - python3-pip
      - keepalived

# TODO: Split to separate file
- name: Load split files
  include_tasks: "{{ item }}"
  with_items:
    - nomad.yaml
    - keepalived.yaml

- name: Read Nomad ACL
  shell:
    cmd: cat /etc/hashicorp/nomad.token | grep 'Secret ID' | awk '{print $4 }'
  register: nomad_global_token

- name: Start Nomad jobs
  shell:
    cmd: nomad job run -address=http://{{ compute_ip }}:4646 -token {{ nomad_global_token.stdout }} {{ item }}
  when: inventory_hostname == compute_ip
  delegate_to: localhost
  with_items:
    - /nomad/example.hcl