---

- name: Install package requirements
  apt:
    name:
      - python3-pip
      - keepalived

- name: Load split files
  include_tasks: "{{ item }}"
  with_items:
    - nomad.yaml
    - keepalived.yaml

- name: Read Nomad ACL
  shell:
    cmd: cat /etc/hashicorp/nomad.token | grep 'Secret ID' | awk '{print $4 }'
  register: nomad_global_token

- name: Create fast storage mount
  ansible.builtin.file:
    path: /mnt/cluster/fast
    state: directory

- name: Start Nomad Infrastructure jobs
  shell:
    cmd: nomad job run -address=http://{{ compute_ip }}:4646 -token {{ nomad_global_token.stdout }} {{ item }}
  when: inventory_hostname == compute_ip
  delegate_to: localhost
  with_items:
    - /nomad/nginx.hcl
    - /nomad/seaweedfs-volumes.hcl
    - /nomad/seaweedfs.hcl
    - /nomad/seaweedfs-filer.hcl
    - /nomad/seaweedfs-csi.hcl

- name: Start Nomad Service jobs
  shell:
    cmd: nomad job run -address=http://{{ compute_ip }}:4646 -token {{ nomad_global_token.stdout }} {{ item }}
  when: inventory_hostname == compute_ip
  delegate_to: localhost
  with_items:
    - /nomad/example.hcl