---

- name: Install package requirements
  apt:
    name:
      - python3-pip
      - glusterfs-server
      - glusterfs-client

- name: Enable glusterd
  ansible.builtin.systemd:
    name: glusterd
    state: started
    enabled: yes

- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ ansible_play_batch }}"

- name: create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: gv0
    bricks: /data/disk1/gv0
    # rebalance: yes
    # replicas: 1
    cluster:
      - cluster1.marms
  run_once: true

- name: start gluster volume
  gluster.gluster.gluster_volume:
    state: started
    name: gv0
  run_once: true

- name: mount gluster volume
  ansible.posix.mount:
    path: /mnt/gluster/gv0
    src: 127.0.0.1:/gv0
    fstype: glusterfs
    state: mounted

- name: Install consul
  command: >-
    hashi-up consul install
    --ssh-target-addr {{ inventory_hostname }}
    --advertise-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
    --ssh-target-key ~/.ssh/id_rsa
    --http-addr 0.0.0.0
    --retry-join {{ compute_ip }}
    --bootstrap-expect {{ ansible_play_batch | length }}
    --server --connect --acl
  delegate_to: localhost

- name: Create storage for consul ACLs
  file:
    path: /mnt/gluster/gv0/consul
    state: directory

- name: Initialize consul ACL
  shell:
    cmd: consul acl bootstrap > /mnt/gluster/gv0/consul/global.token
    creates: /mnt/gluster/gv0/consul/global.token

- name: Install nomad
  command: >-
    hashi-up nomad install
    --ssh-target-addr {{ inventory_hostname }}
    --ssh-target-key ~/.ssh/id_rsa
    --server --client
  delegate_to: localhost